# Generated by Django 3.2 on 2022-05-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.CharField(max_length=50)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_rank', serialize=False, to='fitbit_signage_app.user')),
                ('rank', models.IntegerField(default=1)),
                ('is_sleep', models.BooleanField(default=False)),
                ('is_steps', models.BooleanField(default=False)),
                ('is_calories', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_goal', models.IntegerField()),
                ('steps_goal', models.IntegerField()),
                ('calories_goal', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to='fitbit_signage_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_score', models.IntegerField()),
                ('sleep_minutes', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('achievement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='fitbit_signage_app.user')),
            ],
        ),
    ]
