# Generated by Django 3.2 on 2022-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_signage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
