# Generated by Django 3.2 on 2022-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_signage_app', '0002_userrank_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyscore',
            name='achievement',
        ),
        migrations.AddField(
            model_name='dailyscore',
            name='weight',
            field=models.FloatField(default=62),
            preserve_default=False,
        ),
    ]
