# Generated by Django 3.2 on 2022-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_signage_app', '0003_auto_20220606_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscore',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
